import { getSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feed'
import Header from '../components/Header'
import Login from '../components/Login'
import Sidebar from '../components/Sidebar'
import Widgets from '../components/Widgets'
import { db } from '../firebase'

export default function Home({ session, posts }) {       // session props is defined in SSR [3:46:00]

  if(!session) {

    return <Login />; 

  } 

  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />

      <main className='flex'>
        {/* To make Login functionality. U need to install NextJs Auth (https://next-auth.js.org/getting-started/example) */}
        {/* Sidebar */}
        <Sidebar />
      
        {/* Feed */}
        <Feed posts={posts} />

        {/* Widget */}
        <Widgets />
    
      </main> 
      
    </div>
  )
}


// SSR Starts (Server side rendering) (3:44:00)
export async function getServerSideProps(context) {     // getServerSideProps(context) here context= request came through when user try to goto my website (rahuldxb.com)
  const session = await getSession(context);


  // Adding SSR [5:25:18]
  const posts = await db.collection('posts').orderBy('timestamp', 'desc').get();
  const docs = posts.docs.map(post => ({
    id: post.id,
    ...post.data(),
    timestamp: null
  }))

  return {
    props: {
      session,
      posts: docs,
    }
  }
}